In [1]:
s = "Hi there Sam!"
x = s.split()
print(x)


['Hi', 'there', 'Sam!']


In [2]:
planet = "Earth"
diameter = 12742
print('The diameter of {} is {}.'.format(planet , diameter))


The diameter of Earth is 12742.


In [3]:
d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}
print(d['k1'][3]["tricky"][3]['target'][3])


hello


In [4]:
import numpy as np
array=np.zeros(10)
print("An array of 10 zeros:")
print(array)


An array of 10 zeros:
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [5]:
import numpy as np
array=np.arange(20,36,2)
print("Array of all the even integers from 20 to 35")
print(array) 


Array of all the even integers from 20 to 35
[20 22 24 26 28 30 32 34]


In [7]:
import numpy as np
x =  np.arange(0, 9).reshape(3,3)
print(x)


[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [8]:
import numpy as np
a = np.array([1, 2, 3])
b = np.array([ 4, 5, 6])
arr = np.concatenate(( a, b))
print(arr)


[1 2 3 4 5 6]


In [9]:
import pandas as pd
data = [['Apple', 100], ['Banana', 15], ['Mango', 150]]
df = pd.DataFrame(data, columns=['Fruit', 'Price'])
df


Fruit  Price
0   Apple    100
1  Banana     15
2   Mango    150

In [10]:
import pandas as pd
pd.date_range(start='1/1/2023', end='10/2/2023')
 


DatetimeIndex(['2023-01-01', '2023-01-02', '2023-01-03', '2023-01-04',
               '2023-01-05', '2023-01-06', '2023-01-07', '2023-01-08',
               '2023-01-09', '2023-01-10',
               ...
               '2023-09-23', '2023-09-24', '2023-09-25', '2023-09-26',
               '2023-09-27', '2023-09-28', '2023-09-29', '2023-09-30',
               '2023-10-01', '2023-10-02'],
              dtype='datetime64[ns]', length=275, freq='D')

In [11]:
import pandas as pd
lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]
df = pd.DataFrame(lists, columns=['S.no','Alphabet', 'Numerical'])
df
 


S.no Alphabet  Numerical
0     1      aaa         22
1     2      bbb         25
2     3      ccc         24